service: checkN
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "dynamoDB:*"
    Resource: "arn:aws:dynamodb:us-west-2:995441987960:table/*"

package:
  individually: true
  exclude:
    - "*/**"

functions:
################### Posts Api ###################
  getPostById:
    handler: js/posts-api/handler.getPostById
    events:
      - http:
          path: posts/{postId}
          method: get
          cors: true
    package:
      include:
        - js/posts-api/getPostById.js
        - js/posts-api/handler.js
        - js/posts-api/responses.js

  getPostsBySearch:
    handler: js/posts-api/handler.getPostsBySearch
    events:
      - http:
          path: posts
          method: get
          cors: true
    package:
      include:
        - js/posts-api/getPostsBySearch.js
        - js/posts-api/handler.js
        - js/posts-api/responses.js

  deletePost:
    handler: js/posts-api/handler.deletePost
    events:
      - http:
          path: posts/{postId}
          method: delete
          cors: true
    package:
      include:
        - js/posts-api/deletePost.js
        - js/posts-api/handler.js
        - js/posts-api/responses.js

  createPost:
    handler: js/posts-api/handler.createPost
    events:
      - http:
          path: posts
          method: post  
          cors: true      
    package:
      include:
        - js/posts-api/createPost.js
        - js/posts-api/handler.js
        - js/posts-api/responses.js
        - node_modules/moment/**

  updatePost:
    handler: js/posts-api/handler.updatePost
    events:
      - http:
          path: posts/{postId}
          method: put
          cors: true
    package:
      include:
        - js/posts-api/updatePost.js
        - js/posts-api/handler.js
        - js/posts-api/responses.js
        - node_modules/moment/**

################### Users Api ###################
  getUserById:
    handler: js/users-api/handler.getUserById
    events:
      - http:
          path: users/{userId}
          method: get
          cors: true
    package:
      include:
        - js/users-api/getUserById.js
        - js/users-api/handler.js
        - js/users-api/responses.js

  getUsersBySearch:
    handler: js/users-api/handler.getUsersBySearch
    events:
      - http:
          path: users
          method: get
          cors: true
    package:
      include:
        - js/users-api/getUsersBySearch.js
        - js/users-api/handler.js
        - js/users-api/responses.js

  deleteUser:
    handler: js/users-api/handler.deleteUser
    events:
      - http:
          path: users/{userId}
          method: delete
          cors: true
    package:
      include:
        - js/users-api/deleteUser.js
        - js/users-api/handler.js
        - js/users-api/responses.js

  createUser:
    handler: js/users-api/handler.createUser
    events:
      - http:
          path: users
          method: post
          cors: true
    package:
      include:
        - js/users-api/createUser.js
        - js/users-api/handler.js
        - js/users-api/responses.js

  updateUser:
    handler: js/users-api/handler.updateUser
    events:
      - http:
          path: users/{userId}
          method: put
          cors: true
    package:
      include:
        - js/users-api/updateUser.js
        - js/users-api/handler.js
        - js/users-api/responses.js

################### Tags Api ###################
  getTagById:
    handler: js/tags-api/handler.getTagById
    events:
      - http:
          path: tags/{tagId}
          method: get
          cors: true
    package:
      include:
        - js/tags-api/getTagById.js
        - js/tags-api/handler.js
        - js/tags-api/responses.js

  getTagsBySearch:
    handler: js/tags-api/handler.getTagsBySearch
    events:
      - http:
          path: tags
          method: get
          cors: true
    package:
      include:
        - js/tags-api/getTagsBySearch.js
        - js/tags-api/handler.js
        - js/tags-api/responses.js

  deleteTag:
    handler: js/tags-api/handler.deleteTag
    events:
      - http:
          path: tags/{tagId}
          method: delete
          cors: true
    package:
      include:
        - js/tags-api/deleteTag.js
        - js/tags-api/handler.js
        - js/tags-api/responses.js

  createTag:
    handler: js/tags-api/handler.createTag
    events:
      - http:
          path: tags
          method: post
          cors: true
    package:
      include:
        - js/tags-api/createTag.js
        - js/tags-api/handler.js
        - js/tags-api/responses.js

  updateTag:
    handler: js/tags-api/handler.updateTag
    events:
      - http:
          path: tags/{tagId}
          method: put
          cors: true
    package:
      include:
        - js/tags-api/updateTag.js
        - js/tags-api/handler.js
        - js/tags-api/responses.js


################### Comments Api ###################
  getCommentsByPostId:
    handler: js/comments-api/handler.getCommentsByPostId
    events:
      - http:
          path: posts/{postId}/comments
          method: get
          cors: true
    package:
      include:
        - js/comments-api/getCommentsByPostId.js
        - js/comments-api/handler.js
        - js/comments-api/responses.js

  getCommentsBySearch:
    handler: js/comments-api/handler.getCommentsBySearch
    events:
      - http:
          path: comments
          method: get
          cors: true
    package:
      include:
        - js/comments-api/getCommentsBySearch.js
        - js/comments-api/handler.js
        - js/comments-api/responses.js

  deleteComment:
    handler: js/comments-api/handler.deleteComment
    events:
      - http:
          path: posts/{postId}/comments/{commentId}
          method: delete
          cors: true
    package:
      include:
        - js/comments-api/deleteComment.js
        - js/comments-api/handler.js
        - js/comments-api/responses.js

  createComment:
    handler: js/comments-api/handler.createComment
    events:
      - http:
          path: posts/{postId}/comments
          method: post
          cors: true
    package:
      include:
        - js/comments-api/createComment.js
        - js/comments-api/handler.js
        - js/comments-api/responses.js
        - node_modules/moment/**

  updateComment:
    handler: js/comments-api/handler.updateComment
    events:
      - http:
          path: posts/{postId}/comments/{commentId}
          method: put
          cors: true
    package:
      include:
        - js/comments-api/updateComment.js
        - js/comments-api/handler.js
        - js/comments-api/responses.js
        - node_modules/moment/**